/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 进程存活 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SQLite 可读写 */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 兼容旧客户端的账号式初始 owner 注册；Android Happy 主路径应使用 device-bootstrap。 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/device-bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Android/Happy 首次启动时用本机设备公钥直接初始化首个 owner，不要求账号、邮箱或密码。 */
        post: operations["deviceBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 密码只校验账号；省略 device_role 时签发未绑定的 Web 只读令牌，禁止声明 Android 写身份。 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/identity-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 返回 terminal 登记密钥的脱敏审计视图；不返回公钥材料。 */
        get: operations["listTerminalIdentityKeys"];
        put?: never;
        /** @description 仅 android_owner 可为 terminal 登记签名公钥并进入轮换双读窗口（ADR-012）；同一公钥重复登记幂等返回既有 key，已 retired 的公钥禁止复用。 */
        post: operations["registerTerminalIdentityKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/identity-keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description 立即撤销一把登记密钥；后续使用该 key 的签名一律 KEY_UNKNOWN_OR_REVOKED。 */
        delete: operations["revokeTerminalIdentityKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description 仅 android_owner 可撤销设备；被撤销设备的 bearer 与 refresh 均立即失效。 */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pairing/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅初始 android_owner 可写入一次本机公钥。 */
        post: operations["bootstrapOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pairing/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pairing/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 仅当前 Android owner 可读取；响应包含待配对设备的公开身份和加密密钥。 */
        get: operations["getPairing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pairing/requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅 android_owner 可批准；重复批准幂等，并发批准只创建一台设备。 */
        post: operations["approvePairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pairing/requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅当前 Android owner 可取消待处理配对请求。 */
        post: operations["cancelPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅 android_owner 可生成；恢复码明文只在此响应返回一次。 */
        post: operations["generateRecoveryCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recovery-codes/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 无 bearer 恢复入口；恢复码一次性消费且限次，成功后撤销既有 Android 写设备。 */
        post: operations["restoreRecoveryCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/terminals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTerminals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 账号脱敏审计分页（Admin 只读），limit 上限 100。 */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 账号在最近 1/7/30 天（UTC 日桶）的白名单用量聚合（ADR-010）。 */
        get: operations["usageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/usage/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 已配对 Terminal 上传单条白名单 usage 事件；usage_key 哈希去重，重复上传返回同一回执。 */
        post: operations["uploadUsageEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaces"];
        put?: never;
        /** @description 仅 android_owner/android 写控制端可登记 Workspace。 */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        /** @description 仅 android_owner/android 写控制端可创建逻辑会话。 */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅 android_owner/android 写控制端可获取当前会话的 fencing epoch。 */
        post: operations["acquireSessionLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSessionSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/delegations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 只读返回 parent Session 的 Delegation 图投影。响应只含状态、child session id、Provider 和加密摘要，不返回任务书或 child 正文。 */
        get: operations["listSessionDelegations"];
        put?: never;
        /** @description 仅 Android 写控制端可创建 proposed 节点。请求只能携带加密任务书和摘要，必须使用 parent 当前 lease_epoch；批准前不会创建 child Session。 */
        post: operations["createSessionDelegation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/delegations/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Android 对 proposed/running 节点执行 approve、reject 或 cancel。决策使用 parent lease；approve 后 child 取得独立 lease。 */
        post: operations["decideDelegation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 账号已认证客户端读取指定会话的 Daemon 安全观察投影。仅返回会话状态、命令状态/稳定错误码和裁剪后的密文封装元数据；不返回 command/terminal/lease 标识、密文、nonce、AAD、路径或 Provider 正文。 */
        get: operations["getSessionDaemonObservation"];
        put?: never;
        /** @description 仅 android_owner/android 写控制端可提交；lease_epoch 必须为当前正 fencing epoch。 */
        post: operations["submitSessionCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/readonly-transport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 仅 web 只读角色可获取当前 Session 绑定 Terminal 的配对公钥，用于一次性 X25519 请求密封。Relay 不返回内容密钥、工作区路径或文件元数据。 */
        get: operations["getWebReadTransport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/readonly-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅 web 角色可提交的一次性加密文件/Git 只读请求。Relay 根据 Session -> Workspace -> Terminal 推导目标，仅保存 opaque envelope，不能读取路径、snapshot token 或内容。 */
        post: operations["submitWebReadRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/readonly-requests/{requestID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 仅原账号 web 角色读取受限请求状态；成功后才返回浏览器临时私钥可解的 response envelope。 */
        get: operations["getWebReadRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/commands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCommand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attachments/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅 Android 写控制端可按序上传附件密文块。Relay 不接收文件名或附件正文，只存白名单 MIME/大小、密文元数据与密文块；请求体上限为 768 KiB。 */
        post: operations["uploadAttachmentChunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attachments/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅 Android 写控制端可幂等完成已完整上传的附件；path id 是唯一附件标识；请求体上限为 32 KiB。 */
        post: operations["completeAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 账号范围 SSE。Last-Event-ID 优先于 after_seq；两者都是 account_event_log 的跨会话单调 cursor，不能使用 session-local event_seq。客户端断线后从该 cursor 严格回放；实时 Hub 仅缩短延迟，SQLite 是恢复事实源。 */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 为已配对 terminal 签发一次性 hello challenge（ADR-012）。challenge 绑定当前 bearer 设备，5 分钟有效且只能被 signed hello 消费一次；跨 Relay 重启保持一次性语义。 */
        get: operations["daemonChallenge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 已配对 terminal 以设备 bearer 协商 N/N-1 协议并登记白名单 Daemon 元数据；不得包含 Workspace 绝对路径、Provider 正文或密钥。 */
        post: operations["daemonHello"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅已协商的 terminal 更新在线状态；Relay 只保留 heartbeat 时间与版本摘要。 */
        post: operations["daemonHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/commands/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 仅目标 terminal 的专用 SSE 命令流。每个 command 均携带由 Relay 从 Session 推导的 opaque workspace_id，Daemon 必须再与本机已确认工作区匹配；不得传输 canonical_root。Last-Event-ID / after_delivery_seq 使用 terminal 范围的 delivery_seq，不能与账号级 /v1/events cursor 混用。 */
        get: operations["streamDaemonCommands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/commands/{id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 目标 terminal 对 received/started/rejected 的幂等确认。started 会重新校验 command 的 lease epoch、instance 与 terminal 归属。 */
        post: operations["acknowledgeDaemonCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/commands/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 目标 terminal 回写命令终态；详细结果必须通过独立、幂等的密文 canonical event 上传，不回显 Provider 正文。 */
        post: operations["resolveDaemonCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/commands/{id}/readonly-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 目标 Terminal 回写 browser 临时公钥可解的文件/Git 结果 envelope。Relay 不把该内容写入 session event 或 SSE。 */
        post: operations["storeWebReadResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daemon/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 目标 terminal 上传与命令绑定的 canonical event；Relay 只存 opaque ciphertext envelope 与白名单索引，event_id 可安全重试。 */
        post: operations["uploadDaemonEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        LoginRequest: {
            email: string;
            password: string;
            /**
             * @description 仅允许 web 或 admin；省略时服务端按 web 只读 token 处理。
             * @enum {string}
             */
            device_role?: "web" | "admin";
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            account_id: string;
            access_token: string;
            refresh_token: string;
            expires_in: number;
            device_id?: string;
        };
        DeviceBoundTokenPair: {
            account_id: string;
            device_id: string;
            access_token: string;
            refresh_token: string;
            expires_in: number;
        };
        RecoveryCodeResponse: {
            recovery_code: string;
        };
        RecoveryRestoreRequest: {
            /** @description 兼容旧客户端；Android Happy 主路径不要求邮箱。 */
            email?: string;
            recovery_code: string;
            display_name: string;
            identity_public_key: string;
            encryption_public_key: string;
            platform?: string;
        };
        RecoveryRestoreResponse: {
            device: components["schemas"]["Device"];
            tokens: components["schemas"]["DeviceBoundTokenPair"];
        };
        BootstrapRequest: {
            display_name: string;
            identity_public_key: string;
            encryption_public_key: string;
            platform?: string;
        };
        PairingCreateRequest: {
            /** @enum {string} */
            role: "android" | "terminal" | "web";
            display_name: string;
            identity_public_key: string;
            encryption_public_key: string;
            platform?: string;
        };
        PairingRequest: {
            id: string;
            /** @enum {string} */
            status: "pending" | "approved" | "cancelled" | "expired";
            role: string;
            display_name?: string;
            identity_public_key?: string;
            encryption_public_key?: string;
            platform?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        Device: {
            id: string;
            /** @enum {string} */
            role: "android_owner" | "android" | "terminal" | "web" | "admin";
            /** @enum {string} */
            status: "active" | "revoked";
            display_name?: string;
            platform?: string;
            /** Format: int64 */
            last_seen_unix_ms?: number;
        };
        DeviceList: {
            devices: components["schemas"]["Device"][];
        };
        Terminal: {
            id: string;
            device_id: string;
            hostname?: string;
            platform?: string;
            status: string;
            /** Format: int64 */
            last_seen_unix_ms?: number;
        };
        TerminalList: {
            terminals: components["schemas"]["Terminal"][];
        };
        UploadUsageEventRequest: {
            /** @description Daemon 对来源事件生成的稳定去重键，Relay 只保存其哈希。 */
            usage_key: string;
            provider: string;
            /** @description 可选会话归属，用于单会话 controls 的白名单用量投影。 */
            session_id?: string;
            /** @description 可选 Provider/model 标识；缺失时客户端必须显示 unavailable，不得推断。 */
            model?: string;
            /** @description UTC 日桶，格式 YYYY-MM-DD。 */
            utc_day: string;
            input_tokens: number;
            output_tokens: number;
            /** @default 0 */
            cache_read_tokens: number;
            /** @default 0 */
            cache_write_tokens: number;
            /** @description 可选首 token 延迟（毫秒），由 Provider timing 的 stepStart→firstToken 派生或直接上报。 */
            ttft_ms?: number;
            /** @description 可选解码吞吐 tok/s，由 output tokens / decode seconds 派生或直接上报。 */
            decode_throughput?: number;
        };
        UsageEventReceipt: {
            /** @description usage_key 的不可逆 SHA-256 十六进制摘要，用于幂等回执。 */
            usage_key_hash: string;
            /** @description false 表示该 usage key 已存在（重复上传），不重复累加。 */
            inserted: boolean;
        };
        UsageSummary: {
            /** @description 聚合窗口天数（1/7/30）。 */
            days: number;
            /** @description 聚合窗口结束的 UTC 日桶。 */
            utc_today: string;
            providers: components["schemas"]["UsageDayAggregate"][];
            total_input_tokens: number;
            total_output_tokens: number;
        };
        UsageDayAggregate: {
            provider: string;
            utc_day: string;
            input_tokens: number;
            output_tokens: number;
            cache_read_tokens: number;
            cache_write_tokens: number;
        };
        Project: {
            id: string;
            fingerprint: string;
            encrypted_name?: string;
        };
        ProjectList: {
            projects: components["schemas"]["Project"][];
        };
        Workspace: {
            id: string;
            project_id: string;
            terminal_id: string;
            branch?: string;
            status?: string;
        };
        WorkspaceList: {
            workspaces: components["schemas"]["Workspace"][];
        };
        CreateWorkspaceRequest: {
            project_id: string;
            terminal_id?: string;
            canonical_root: string;
            branch?: string;
            status?: string;
        };
        Session: {
            id: string;
            workspace_id: string;
            status: string;
            /** Format: int64 */
            last_seq?: number;
            provider?: string;
        };
        SessionList: {
            sessions: components["schemas"]["Session"][];
        };
        CreateSessionRequest: {
            workspace_id: string;
            provider?: string;
        };
        LeaseResponse: {
            session_id: string;
            /** Format: int64 */
            lease_epoch: number;
        };
        SessionSnapshot: {
            session: components["schemas"]["Session"];
            events: components["schemas"]["CipherEvent"][];
        };
        /** @description Flutter P2-F 只读观察投影。该资源不返回会话/命令/Terminal 的 opaque 标识，也不返回原始密文 envelope。 */
        DaemonSessionObservation: {
            session: components["schemas"]["DaemonObservationSession"];
            commands: components["schemas"]["DaemonCommandObservation"][];
            events: components["schemas"]["DaemonCipherEventObservation"][];
        };
        DaemonObservationSession: {
            status: string;
            provider?: string;
            /** Format: int64 */
            last_seq: number;
        };
        DaemonCommandObservation: {
            /** @description 已登记命令种类；客户端未知种类必须显示通用只读占位。 */
            kind: string;
            /** @enum {string} */
            status: "accepted" | "running" | "succeeded" | "failed" | "cancelled" | "rejected" | "expired";
            /** @enum {string} */
            delivery_state: "queued" | "received" | "started" | "rejected" | "resolved";
            /** @description 仅协议登记的稳定错误码；未知值在 Relay 侧归一为 DAEMON_EXECUTION_FAILED。 */
            error_code?: string;
        };
        DaemonCipherEventObservation: {
            /** Format: int64 */
            event_seq: number;
            /** @enum {string} */
            event_type: "session.lifecycle" | "turn.started" | "message.delta" | "message.completed" | "tool.call" | "tool.result" | "usage.updated" | "file.changed" | "git.snapshot" | "command.updated" | "unknown";
            envelope: components["schemas"]["CipherEnvelopeMetadata"];
        };
        /** @description 仅证明 Relay 已验证版本化密文封装，不包含 key_id、nonce、ciphertext、aad_hash 或任何明文。 */
        CipherEnvelopeMetadata: {
            /** @enum {string} */
            state: "verified" | "opaque";
            /** @enum {string} */
            algorithm?: "v1-aes256gcm-hkdfsha256";
            payload_version?: number;
        };
        /** @description parent Session 的安全 Delegation 投影。task_envelope 永不出现在此资源或事件流中。 */
        Delegation: {
            id: string;
            parent_session_id: string;
            child_session_id?: string;
            target_provider: string;
            /** @enum {string} */
            status: "proposed" | "approved" | "running" | "completed" | "failed" | "cancelled" | "rejected";
            /** @description 客户端加密摘要；Relay 不解密、不搜索。 */
            summary_envelope: Record<string, never>;
            summary_envelope_sha256: string;
        };
        DelegationList: {
            delegations: components["schemas"]["Delegation"][];
        };
        /** @description 任务书与摘要必须为完整加密 envelope；不得包含任务正文、路径、子会话消息或附件正文。 */
        CreateDelegationRequest: {
            target_workspace_id: string;
            target_terminal_id?: string;
            target_provider: string;
            task_envelope: Record<string, never>;
            summary_envelope: Record<string, never>;
            idempotency_key: string;
            /** Format: int64 */
            lease_epoch: number;
        };
        DelegationDecisionRequest: {
            /** @enum {string} */
            decision: "approve" | "reject" | "cancel";
            idempotency_key: string;
            /** Format: int64 */
            lease_epoch: number;
        };
        CipherEvent: {
            /** Format: int64 */
            event_seq: number;
            event_type: string;
            envelope: Record<string, never>;
        };
        SubmitCommandRequest: {
            /** @description 仅在目标 Terminal 声明对应 capability 时投递；session.kill 仅适用于 Daemon 明确拥有的本机 Provider 进程树，不能用 session.abort 替代。 */
            kind: string;
            idempotency_key: string;
            /** Format: int64 */
            lease_epoch: number;
            target_instance_id?: string;
            target_terminal_id?: string;
            ciphertext?: Record<string, never>;
        };
        WebReadTransport: {
            terminal_id: string;
            /** @description Session 关联的 opaque Workspace ID，不是本机路径。 */
            workspace_id: string;
            /** @description 配对 Terminal 的 X25519 公钥，不是内容密钥。 */
            encryption_public_key: string;
            /** @enum {string} */
            algorithm: "v1-x25519-hkdfsha256-aes256gcm";
        };
        WebReadRequest: {
            request_id: string;
            /** @enum {string} */
            kind: "file.tree" | "file.read" | "code.read" | "git.status" | "git.changes" | "git.diff";
            envelope: components["schemas"]["WebReadRequestEnvelope"];
        };
        WebReadRequestEnvelope: {
            /** @enum {string} */
            alg: "v1-x25519-hkdfsha256-aes256gcm";
            payload_version: number;
            ephemeral_public_key: string;
            nonce: string;
            ciphertext: string;
            aad_hash: string;
        };
        WebReadReceipt: {
            request_id: string;
            kind: string;
            /** @enum {string} */
            status: "accepted" | "running" | "succeeded" | "failed" | "rejected";
        };
        WebReadStatus: {
            request_id: string;
            kind: string;
            /** @enum {string} */
            status: "accepted" | "running" | "succeeded" | "failed" | "rejected";
            error_code?: string;
            envelope?: components["schemas"]["WebReadResponseEnvelope"];
        };
        WebReadResponseEnvelope: {
            /** @enum {string} */
            alg: "v1-x25519-hkdfsha256-aes256gcm";
            payload_version: number;
            nonce: string;
            ciphertext: string;
            aad_hash: string;
        };
        Command: {
            id: string;
            kind: string;
            status: string;
            idempotency_key: string;
            /**
             * Format: int64
             * @description 0 仅用于受限 Web 只读请求；所有 Android 写控制命令必须大于 0 并通过 lease fencing。
             */
            lease_epoch?: number;
            target_terminal_id?: string;
        };
        DaemonHelloRequest: {
            protocol_version: number;
            daemon_version: string;
            hostname: string;
            platform: string;
            capabilities: string[];
            signature?: components["schemas"]["TerminalSignature"];
        };
        DaemonHelloResponse: {
            terminal_id: string;
            protocol_version: number;
            min_protocol_version: number;
            heartbeat_interval_seconds: number;
            /** Format: int64 */
            after_delivery_seq: number;
            /** @description ADR-012 能力协商：optional 兼容窗口为 [bearer, signature_v1]；required 窗口只剩 [signature_v1]。客户端据此选择认证方式，不得自行猜测。 */
            auth_modes?: ("bearer" | "signature_v1")[];
        };
        DaemonHeartbeatRequest: {
            protocol_version: number;
            signature?: components["schemas"]["TerminalSignature"];
        };
        DaemonHeartbeatResponse: {
            terminal_id: string;
            /** Format: int64 */
            server_time_unix_ms: number;
        };
        DaemonCommandDelivery: {
            /** Format: int64 */
            delivery_seq: number;
            command: components["schemas"]["DaemonDeliveredCommand"];
        };
        DaemonDeliveredCommand: {
            id: string;
            session_id: string;
            /** @description Relay 从 Session 推导的 opaque ID；不是本机路径，也不能替代 Daemon 本机确认。 */
            workspace_id: string;
            kind: string;
            /** Format: int64 */
            lease_epoch: number;
            target_instance_id?: string;
            target_terminal_id: string;
            ciphertext: Record<string, never>;
        };
        DaemonCommandAckRequest: {
            protocol_version: number;
            /** Format: int64 */
            delivery_seq: number;
            /** @enum {string} */
            ack_kind: "received" | "started" | "rejected";
            error_code?: string;
            signature?: components["schemas"]["TerminalSignature"];
        };
        DaemonCommandResultRequest: {
            protocol_version: number;
            /** Format: int64 */
            delivery_seq: number;
            /** @enum {string} */
            status: "succeeded" | "failed" | "cancelled";
            error_code?: string;
            signature?: components["schemas"]["TerminalSignature"];
        };
        DaemonCommandReceipt: {
            command_id: string;
            /** Format: int64 */
            delivery_seq: number;
            ack_kind: string;
            status: string;
            error_code?: string;
        };
        DaemonWebReadResponseRequest: {
            protocol_version: number;
            /** Format: int64 */
            delivery_seq: number;
            envelope: components["schemas"]["WebReadResponseEnvelope"];
            signature?: components["schemas"]["TerminalSignature"];
        };
        DaemonEventUploadRequest: {
            protocol_version: number;
            event_id: string;
            command_id: string;
            session_id: string;
            /** @enum {string} */
            event_type: "session.lifecycle" | "turn.started" | "message.delta" | "message.completed" | "tool.call" | "tool.result" | "usage.updated" | "file.changed" | "git.snapshot" | "command.updated";
            envelope: components["schemas"]["OpaqueCipherEnvelope"];
            signature?: components["schemas"]["TerminalSignature"];
        };
        DaemonEventUploadResponse: {
            event_id: string;
            /** Format: int64 */
            event_seq: number;
            idempotent: boolean;
        };
        /** @description Terminal 签名认证的 additive 请求字段。canonical bytes 冻结为 protocol_version|device_id|request_method|request_path|timestamp_ms|nonce|sha256(body)|key_id。 body_hash 覆盖"删除顶层 signature 成员后的紧凑 UTF-8 JSON 原文字节"，两端都不得把 signature 字段纳入哈希（否则签名覆盖自身，构成循环依赖）。hello 的 nonce 必须是 /v1/daemon/challenge 预签发的一次性 challenge。字段在签名模式启用后由 Relay 强制校验； optional 兼容窗口内允许旧 bearer 客户端忽略。 */
        TerminalSignature: {
            protocol_version?: number;
            key_id?: string;
            /** Format: int64 */
            timestamp_ms?: number;
            nonce?: string;
            body_hash?: string;
            signature?: string;
        };
        DaemonChallengeResponse: {
            challenge: string;
            /** Format: int64 */
            expires_at_unix_ms: number;
        };
        TerminalIdentityKeyRequest: {
            /** @description Ed25519 公钥（base64/base64url）；私钥永远不离开 Terminal 本机。 */
            identity_public_key: string;
        };
        TerminalIdentityKeyView: {
            key_id: string;
            device_id: string;
            /** @enum {string} */
            status: "active" | "retired";
            /** Format: int64 */
            created_at_unix_ms: number;
            /** Format: int64 */
            retired_at_unix_ms?: number;
        };
        TerminalIdentityKeyList: {
            keys: components["schemas"]["TerminalIdentityKeyView"][];
        };
        /** @description Relay 不解密此对象；字段只证明其为版本化 ciphertext envelope，禁止携带明文正文、路径、prompt 或 Provider 原始响应。 */
        OpaqueCipherEnvelope: {
            alg: string;
            key_id: string;
            nonce: string;
            ciphertext: string;
            aad_hash: string;
            payload_version: number;
        } & {
            [key: string]: unknown;
        };
        /** @description 不包含 filename 或明文内容；metadata_ciphertext 与 ciphertext 均为客户端加密后的 base64 字节串。 */
        AttachmentChunkUploadRequest: {
            attachment_id: string;
            session_id: string;
            /** @enum {string} */
            mime_type: "image/png" | "image/jpeg" | "image/webp" | "text/plain" | "text/markdown";
            /** Format: int64 */
            byte_size: number;
            /** @enum {string} */
            compression: "none" | "gzip";
            /** Format: byte */
            metadata_ciphertext: string;
            chunk_index: number;
            total_chunks: number;
            /** Format: byte */
            ciphertext: string;
            idempotency_key: string;
            /** Format: int64 */
            lease_epoch: number;
        };
        AttachmentCompleteRequest: {
            session_id: string;
            total_chunks: number;
            idempotency_key: string;
            /** Format: int64 */
            lease_epoch: number;
        };
        AttachmentReceipt: {
            attachment_id: string;
            chunk_index: number;
            /** @enum {string} */
            status: "pending" | "completed";
            idempotent: boolean;
        };
        CapabilityItem: {
            name: string;
            /** @enum {string} */
            status: "native" | "emulated" | "unsupported";
            reason?: string;
        };
        CapabilityProvider: {
            kind: string;
            version: string;
            available: boolean;
            capabilities: components["schemas"]["CapabilityItem"][];
        };
        CapabilityProvidersResponse: {
            providers: components["schemas"]["CapabilityProvider"][];
        };
    };
    responses: {
        /** @description 请求体、游标或参数不符合契约。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 缺少、失效或被重放的认证凭据。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 设备已撤销、只读或不具备当前操作所需角色。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 幂等键、租约或 bootstrap 状态冲突。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求的资源不存在或不属于当前账号。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 恢复码失败次数超过冷却阈值。 */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求体超过该接口允许的安全上限。 */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceBoundTokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    deviceBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryRestoreResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTerminalIdentityKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description registered keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalIdentityKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    registerTerminalIdentityKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerminalIdentityKeyRequest"];
            };
        };
        responses: {
            /** @description registered key */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalIdentityKeyView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeTerminalIdentityKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    bootstrapOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description owner device */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    createPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingCreateRequest"];
            };
        };
        responses: {
            /** @description pending */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingRequest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPairing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pairing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    approvePairing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelPairing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    generateRecoveryCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description recovery code shown once to the current owner */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    restoreRecoveryCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryRestoreRequest"];
            };
        };
        responses: {
            /** @description recovered owner device and a new device-bound token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryRestoreResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listTerminals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description terminals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description redacted audit entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        audit: {
                            id: number;
                            action: string;
                            metadata?: string;
                        }[];
                    };
                };
            };
        };
    };
    usageSummary: {
        parameters: {
            query?: {
                days?: 1 | 7 | 30;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description usage summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadUsageEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUsageEventRequest"];
            };
        };
        responses: {
            /** @description usage event receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageEventReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description created workspace */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description created session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    acquireSessionLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current lease */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getSessionSnapshot: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSessionDelegations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description parent delegation graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DelegationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createSessionDelegation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDelegationRequest"];
            };
        };
        responses: {
            /** @description proposed delegation */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delegation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    decideDelegation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelegationDecisionRequest"];
            };
        };
        responses: {
            /** @description updated delegation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delegation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getSessionDaemonObservation: {
        parameters: {
            query?: {
                /** @description 仅返回严格大于该会话事件序号的安全事件元数据；命令状态始终返回当前完整安全投影。 */
                after_seq?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description daemon observation projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonSessionObservation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    submitSessionCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitCommandRequest"];
            };
        };
        responses: {
            /** @description accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Command"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getWebReadTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current terminal public transport metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebReadTransport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    submitWebReadRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebReadRequest"];
            };
        };
        responses: {
            /** @description accepted web read request */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebReadReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getWebReadRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                requestID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description web read state and optional opaque response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebReadStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description command */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Command"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    uploadAttachmentChunk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentChunkUploadRequest"];
            };
        };
        responses: {
            /** @description chunk accepted or idempotently replayed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    completeAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentCompleteRequest"];
            };
        };
        responses: {
            /** @description attachment completed or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description attachment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityProvidersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                /** @description Last-Event-ID 缺失时使用的账号级 cursor；名称为兼容保留，不是 session event_seq。 */
                after_seq?: number;
            };
            header?: {
                /** @description 上次已处理的账号级 cursor；值必须是非负整数。 */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    daemonChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description issued challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonChallengeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    daemonHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaemonHelloRequest"];
            };
        };
        responses: {
            /** @description negotiated terminal state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonHelloResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description terminal protocol is below the supported compatibility window */
            426: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    daemonHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaemonHeartbeatRequest"];
            };
        };
        responses: {
            /** @description heartbeat accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonHeartbeatResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description terminal protocol is below the supported compatibility window */
            426: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamDaemonCommands: {
        parameters: {
            query?: {
                after_delivery_seq?: number;
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description daemon command SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["DaemonCommandDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    acknowledgeDaemonCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaemonCommandAckRequest"];
            };
        };
        responses: {
            /** @description ack state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonCommandReceipt"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    resolveDaemonCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaemonCommandResultRequest"];
            };
        };
        responses: {
            /** @description result state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonCommandReceipt"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    storeWebReadResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaemonWebReadResponseRequest"];
            };
        };
        responses: {
            /** @description opaque web read response stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonCommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    uploadDaemonEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaemonEventUploadRequest"];
            };
        };
        responses: {
            /** @description event accepted or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaemonEventUploadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
